#-------------------------------
# General Site Settings
title: Pea&Pig
logo: logo.svg # You can add own logo.
description: Pea&Pig are always happy


#-------------------------------
# Author Settings
author:
  name: wanglongke
  image: 01.jpg
  say-hello: <center><strong>Wang Longke</strong></center>
  bio: 我是一名算法工程师，在大连理工大学数学科学学院（https://www.dlut.edu.cn/）拿到了学士与硕士学位，所学专业为<strong>计算数学</strong>. 
  主要研究方向为物理仿真与渲染，三维曲面重建，数字化人体表达。


#-------------------------------
# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
# facebook: https://facebook.com/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# instagram: https://instagram.com/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
